name: Benchmarks

on:
  push:
    branches:
      - heshamMassoud-actions-test
    paths:
      - '*/*.java' # Only run workflow when files changed contain Java files.

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run benchmarks
        run: ./gradlew clean setLibraryVersion benchmark benchmarkCommit
        env:
          SOURCE_PROJECT_KEY: java-sync-source
          SOURCE_CLIENT_ID:  ${{ secrets.SOURCE_CLIENT_ID }}
          SOURCE_CLIENT_SECRET:  ${{ secrets.SOURCE_CLIENT_SECRET }}
          TARGET_PROJECT_KEY: java-sync-target
          TARGET_CLIENT_ID: ${{ secrets.TARGET_CLIENT_ID }}
          TARGET_CLIENT_SECRET: ${{ secrets.TARGET_CLIENT_SECRET }}
          CI_BUILD_DIR: ${{ secrets.CI_BUILD_DIR }}
          GRGIT_USER: ${{ secrets.GRGIT_USER }}
