name: Benchmarks

on:
  push:
    branches:
      - master
    paths:
      - '!/docs/*' # Don't run workflow when files are only in the /docs directory
      - '!README.md' # Don't run workflow when files are only README.md
      - '!README.md' # Don't run workflow when files are only README.md

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run benchmarks
      run: ./gradlew clean setLibraryVersion benchmark benchmarkCommit
      env:
        SOURCE_PROJECT_KEY: java-sync-source
        SOURCE_CLIENT_ID:  ${{ secrets.SOURCE_CLIENT_ID }}
        SOURCE_CLIENT_SECRET:  ${{ secrets.SOURCE_CLIENT_SECRET }}
        TARGET_PROJECT_KEY: java-sync-target
        TARGET_CLIENT_ID: ${{ secrets.TARGET_CLIENT_ID }}
        TARGET_CLIENT_SECRET: ${{ secrets.TARGET_CLIENT_SECRET }}
        BINTRAY_USER: commercetools
        BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        CI_BUILD_DIR: ${{ secrets.CI_BUILD_DIR }}
        GRGIT_USER: ${{ secrets.GRGIT_USER }}
